version: "3.8"

services:
  web:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_local
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    env_file:
      - .env.local
    container_name: postgresql
    image: postgres:17.3
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-data:
